apiVersion: v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: zenith-web-deployment
        image: maguran/zenith-web
        ports:
          - containerPort: 4200

